import { MD3LightTheme } from "react-native-paper";
import themeFonts from "./fonts";

export const myTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#005A57",
    surfaceTint: "#006E27",
    onPrimary: "#FFFFFF",
    primaryContainer: "#005A5734",
    onPrimaryContainer: "#005A5714",
    secondary: "#B68239",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#b375465e",
    onSecondaryContainer: "#6A5E00",
    tertiary: "#DFB44F",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#FFFFFF",
    onTertiaryContainer: "#747676",
    error: "#F16363",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    background: "#F4FCEF",
    onBackground: "#171D16",
    surface: "#F4FCEF",
    onSurface: "#171D16",
    surfaceVariant: "#f4f4f4",
    onSurfaceVariant: "#676c66ff",
    outline: "#a8a8a8ff",
    outlineVariant: "#BDCAB9",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#2B322A",
    inverseOnSurface: "#ECF3E7",
    inversePrimary: "#63DF75",
    primaryFixed: "#80FC8E",
    onPrimaryFixed: "#002107",
    primaryFixedDim: "#63DF75",
    onPrimaryFixedVariant: "#00531B",
    secondaryFixed: "#FEE31C",
    onSecondaryFixed: "#201C00",
    secondaryFixedDim: "#DFC700",
    onSecondaryFixedVariant: "#514700",
    tertiaryFixed: "#E2E2E2",
    onTertiaryFixed: "#1A1C1C",
    tertiaryFixedDim: "#C6C6C7",
    onTertiaryFixedVariant: "#454747",
    surfaceDim: "#D5DCD0",
    surfaceBright: "#F4FCEF",
    surfaceContainerLowest: "#FFFFFF",
    surfaceContainerLow: "#EFF6E9",
    surfaceContainer: "#f2f2f2ff",
    surfaceContainerHigh: "#ebebebff",
    surfaceContainerHighest: "#e0e0e0ff",
  },

  fonts: themeFonts,
};

export default myTheme;
